/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question (non-streaming) */
        post: operations["post_chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question (SSE stream) */
        post: operations["post_chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The full document behind a citation */
        get: operations["get_document_api_corpus__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The gold eval set */
        get: operations["get_questions_api_evals_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Past eval runs */
        get: operations["get_runs_api_evals_runs_get"];
        put?: never;
        /**
         * Start an eval run over the gold set
         * @description Kick off a run and return immediately with its id.
         *
         *     202, not 200: the run has been accepted, not completed. The client then opens
         *     `/evals/runs/{id}/stream` to watch it and `/evals/runs/{id}` to read the final result.
         */
        post: operations["post_run_api_evals_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-question results for one run */
        get: operations["get_run_api_evals_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evals/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Follow a running eval */
        get: operations["stream_run_api_evals_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and configured lanes */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerClaim
         * @description A span of the answer plus what backs it.
         *
         *     Phase 4 populates this properly; Phase 1a may emit a single claim covering the whole answer.
         *     `text` is a **verbatim substring** of `ChatResponse.answer` — Phase 4's hover-to-highlight has
         *     to locate it, and a paraphrase turns an index lookup into a fuzzy-match problem.
         */
        AnswerClaim: {
            /** Citation Ids */
            citation_ids: string[];
            /** Text */
            text: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Message */
            message: string;
            /** Plan Year */
            plan_year?: number | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Abstained */
            abstained: boolean;
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Claims */
            claims: components["schemas"]["AnswerClaim"][];
            /** Conversation Id */
            conversation_id: string;
            /** Message Id */
            message_id: string;
            /** Trace */
            trace: components["schemas"]["TraceStep"][];
            usage?: components["schemas"]["Usage"] | null;
        };
        /**
         * Citation
         * @description One source behind part of an answer.
         */
        Citation: {
            /** Chunk Id */
            chunk_id?: string | null;
            /** Doc Id */
            doc_id?: string | null;
            /** Id */
            id: string;
            /** Score */
            score?: number | null;
            /** Snippet */
            snippet: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "reference" | "structured_api" | "web";
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /** CitationEvent */
        CitationEvent: {
            citation: components["schemas"]["Citation"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "citation";
        };
        /**
         * CorpusDocument
         * @description One corpus record, for citation drill-down.
         *
         *     `meta` carries the per-source fields (`page`, `section_number`, `effective_date`, `pub_id`, …)
         *     as a passthrough dict. That is the opposite of the flat-optional-columns choice in
         *     `chunking/models.py`, and deliberately so: that choice was about Arrow/LanceDB filterability
         *     (docs/lancedb.md), which has no analogue in a JSON response. Flattening here would restate the
         *     per-source vocabulary in a third place.
         */
        CorpusDocument: {
            /** Bite */
            bite: string;
            /** Id */
            id: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /**
             * Source
             * @enum {string}
             */
            source: "healthcare_gov" | "medicare_ncd" | "medicare_pubs";
            /** Text */
            text: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** CorpusStatus */
        CorpusStatus: {
            /** Chunks */
            chunks: number;
            /** Chunks Built */
            chunks_built: boolean;
            /** Documents */
            documents: number;
            /**
             * Source
             * @enum {string}
             */
            source: "healthcare_gov" | "medicare_ncd" | "medicare_pubs";
        };
        /** DoneEvent */
        DoneEvent: {
            response: components["schemas"]["ChatResponse"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * Code
             * @default internal
             * @enum {string}
             */
            code: "internal" | "timeout" | "cancelled" | "bad_request";
            /** Message */
            message: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** EvalQuestionResult */
        EvalQuestionResult: {
            /**
             * Abstained
             * @default false
             */
            abstained: boolean;
            /** Error */
            error?: string | null;
            /**
             * Expected Abstain
             * @default false
             */
            expected_abstain: boolean;
            /** Expected Source Type */
            expected_source_type?: ("reference" | "structured_api" | "web") | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Passed */
            passed: boolean;
            /** Question Id */
            question_id: string;
            /** Rank */
            rank?: number | null;
            /** Retrieved Doc Ids */
            retrieved_doc_ids?: string[];
            /** Tools Used */
            tools_used?: string[];
        };
        /** EvalQuestionsResponse */
        EvalQuestionsResponse: {
            /** Count */
            count: number;
            /** Questions */
            questions: components["schemas"]["GoldQuestion"][];
        };
        /** EvalRun */
        EvalRun: {
            /** Chunker Snapshot Id */
            chunker_snapshot_id?: {
                [key: string]: string;
            };
            /** Config Fingerprint */
            config_fingerprint?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Id */
            id: string;
            /** Live */
            live?: boolean | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Model */
            model?: string | null;
            /** N Passed */
            n_passed: number;
            /** N Questions */
            n_questions: number;
            /** Results */
            results: components["schemas"]["EvalQuestionResult"][];
            /** Runner */
            runner: string;
            /** Structured */
            structured?: boolean | null;
            /** Toolset */
            toolset?: string | null;
            /** Vectors Snapshot Id */
            vectors_snapshot_id?: string | null;
            /** Web */
            web?: boolean | null;
        };
        /**
         * EvalRunEventEnvelope
         * @description Same schema-only trick as `StreamEventEnvelope`, for the eval-progress stream.
         */
        EvalRunEventEnvelope: {
            /** Event */
            event: components["schemas"]["EvalRunStarted"] | components["schemas"]["EvalRunProgress"] | components["schemas"]["EvalRunFinished"] | components["schemas"]["EvalRunFailed"];
        };
        /** EvalRunFailed */
        EvalRunFailed: {
            /** Message */
            message: string;
            /** Run Id */
            run_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "failed";
        };
        /** EvalRunFinished */
        EvalRunFinished: {
            run: components["schemas"]["EvalRun"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "finished";
        };
        /**
         * EvalRunProgress
         * @description One tick of a running eval, streamed to the dashboard while it works.
         */
        EvalRunProgress: {
            /** Completed */
            completed: number;
            result: components["schemas"]["EvalQuestionResult"];
            /** Run Id */
            run_id: string;
            /** Total */
            total: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "progress";
        };
        /** EvalRunStarted */
        EvalRunStarted: {
            /** Run Id */
            run_id: string;
            /** Total */
            total: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "started";
        };
        /** EvalRunSummary */
        EvalRunSummary: {
            /** Chunker Snapshot Id */
            chunker_snapshot_id?: {
                [key: string]: string;
            };
            /** Config Fingerprint */
            config_fingerprint?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Id */
            id: string;
            /** Live */
            live?: boolean | null;
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Model */
            model?: string | null;
            /** N Passed */
            n_passed: number;
            /** N Questions */
            n_questions: number;
            /** Runner */
            runner: string;
            /** Structured */
            structured?: boolean | null;
            /** Toolset */
            toolset?: string | null;
            /** Vectors Snapshot Id */
            vectors_snapshot_id?: string | null;
            /** Web */
            web?: boolean | null;
        };
        /** GoldQuestion */
        GoldQuestion: {
            /** Answer Key Facts */
            answer_key_facts?: string[];
            /** Becomes Answerable At Phase */
            becomes_answerable_at_phase?: string | null;
            /** Corpus */
            corpus?: ("healthcare_gov" | "medicare_ncd" | "medicare_pubs") | null;
            /** Difficulty */
            difficulty?: ("easy" | "medium" | "hard") | null;
            /**
             * Expected Abstain
             * @default false
             */
            expected_abstain: boolean;
            /** Expected Answer */
            expected_answer?: string | null;
            /** Expected Cells */
            expected_cells?: string[];
            /** Expected Doc Ids */
            expected_doc_ids?: string[];
            /** Expected Lane Detail */
            expected_lane_detail?: ("mirror" | "live") | null;
            /** Expected Snippet */
            expected_snippet?: string | null;
            /** Expected Source Type */
            expected_source_type?: ("reference" | "structured_api" | "web") | null;
            /** Expected Table */
            expected_table?: string | null;
            /** Expected Tools */
            expected_tools?: string[];
            /** Id */
            id: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Plan Year */
            plan_year?: number | null;
            /** Question */
            question: string;
            /**
             * Volatile
             * @default false
             */
            volatile: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Corpora */
            corpora: components["schemas"]["CorpusStatus"][];
            /** Lanes */
            lanes: components["schemas"]["LaneStatus"][];
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Stub */
            stub: boolean;
            /** Version */
            version: string;
        };
        /**
         * LaneStatus
         * @description Whether one routing lane is wired up, and why not when it isn't.
         */
        LaneStatus: {
            /** Configured */
            configured: boolean;
            /** Detail */
            detail: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "reference" | "structured_api" | "web";
        };
        /** StartEvent */
        StartEvent: {
            /** Conversation Id */
            conversation_id: string;
            /** Message Id */
            message_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "start";
        };
        /** StepEvent */
        StepEvent: {
            step: components["schemas"]["TraceStep"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
        };
        /**
         * StreamEventEnvelope
         * @description Schema-only carrier so the SSE union reaches `components.schemas`.
         *
         *     This is docs/frontend_plan.md §4.5's second gotcha made concrete: FastAPI only ever sees a
         *     `StreamingResponse`, so the union has to be attached to a route's `responses=` metadata — and
         *     that takes a *model*, not a bare annotated union. Without this wrapper the union never lands in
         *     `openapi.json` and the generated TypeScript silently lacks it.
         *
         *     Never sent on the wire. `frontend/src/api/client.ts` unwraps it as
         *     `components["schemas"]["StreamEventEnvelope"]["event"]`.
         */
        StreamEventEnvelope: {
            /** Event */
            event: components["schemas"]["StartEvent"] | components["schemas"]["StepEvent"] | components["schemas"]["TokenEvent"] | components["schemas"]["CitationEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["ErrorEvent"];
        };
        /** TokenEvent */
        TokenEvent: {
            /** Delta */
            delta: string;
            /**
             * Reset
             * @default false
             */
            reset: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token";
        };
        /**
         * TraceStep
         * @description One step of the agent loop, as the trace panel shows it.
         *
         *     Note that `kind` is the *shape* of the step and `tool` is which tool ran: a retrieval is
         *     `kind="tool_call", tool="retrieve"`, not `kind="retrieve"`. The UI labels a step
         *     `tool ?? kind`.
         */
        TraceStep: {
            /** Duration Ms */
            duration_ms?: number | null;
            /** Index */
            index: number;
            /** Input */
            input?: {
                [key: string]: unknown;
            } | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "plan" | "tool_call" | "tool_result" | "synthesis";
            /** Summary */
            summary: string;
            /** Tokens */
            tokens?: number | null;
            /** Tool */
            tool?: string | null;
        };
        /**
         * Usage
         * @description Cost and latency for one message.
         *
         *     Every field is optional because there is not always a model behind an answer: the Phase 0 stub
         *     has none, and Phase 1a's lexical retrieval has no token cost. Phase 4 surfaces these per run.
         */
        Usage: {
            /** Input Tokens */
            input_tokens?: number | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Model */
            model?: string | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Total Tokens */
            total_tokens?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events. Each frame's `data:` is one `StreamEvent`, discriminated by its `type` field. The `done` event carries the complete `ChatResponse` and is authoritative — clients replace their incrementally-built state with it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEventEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_document_api_corpus__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusDocument"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_questions_api_evals_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalQuestionsResponse"];
                };
            };
        };
    };
    get_runs_api_evals_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunSummary"][];
                };
            };
        };
    };
    post_run_api_evals_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunStarted"];
                };
            };
        };
    };
    get_run_api_evals_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_api_evals_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events for one run: `started`, then one `progress` per question, then `finished` (carrying the complete run) or `failed`. Events are replayed from the beginning, so connecting late loses nothing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["EvalRunEventEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
